# =============================================================================
# DATASOURCE (PostgreSQL)
# =============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/aicareer_db
spring.datasource.username=postgres
spring.datasource.password=KRNSmo0Rnx
#KRMSnoQRnx
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

# =============================================================================
# JPA (??? ???????? ?????????????)
# =============================================================================
spring.jpa.hibernate.ddl-auto=update
#validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=aicareer

# =============================================================================
# APPLICATION SETTINGS
# =============================================================================
app.logging.level=${APP_LOGGING_LEVEL:INFO}
app.name=${APP_NAME:AiCareer}
app.version=${APP_VERSION:1.0.0}

# =============================================================================
# EXTERNAL SERVICES
# =============================================================================
# GigaChat (????? ?????????????? ? @ConfigurationProperties)
gigachat.client-id=${GIGACHAT_CLIENT_ID:}
gigachat.client-secret=${GIGACHAT_CLIENT_SECRET:}
gigachat.scope=GIGACHAT_API_PERS
gigachat.timeout-seconds=30

spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

#????? ????? ? ???????
debug=false
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR
logging.level.org.apache.kafka=ERROR
logging.level.com.zaxxer.hikari=ERROR

logging.level.com.aicareer=INFO