CREATE TABLE IF NOT EXISTS cv_data (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    file_path VARCHAR(500),
    information TEXT,
    uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cv_data_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);